### ISSUE TITLE
Unable to build python module

### ISSUE THREAD

**Issue by sbertin-telular** [cminyard/serialsim#1]
After cloning, I ran the reconf script from ser2net, configure, and make. It failed to build and appears that there is a file missing. Full log follows.

✔ ~/workspace/serialsim/swig [master|✔] 
15:37 $ ../../ser2net/reconf 
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
configure.ac:4: installing './ar-lib'
configure.ac:3: installing './compile'
configure.ac:5: installing './config.guess'
configure.ac:5: installing './config.sub'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
✔ ~/workspace/serialsim/swig [master|…13] 
15:37 $ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for ANSI C header files... (cached) yes
checking for swig... no
checking for swig3.0... no
checking for swig2.0... no
checking for python3... /usr/bin/python3
checking for python3... (cached) /usr/bin/python3
checking for a version of Python >= '2.1.0'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python3.7m
checking for Python library path... -L/usr/lib -lpython3.7m
checking for Python site-packages path... /usr/lib/python3/dist-packages
checking python extra libraries... -lcrypt -lpthread -ldl  -lutil -lm
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking consistency of all components of python development environment... yes
checking for python version... 3.7.5
checking for python threads... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
✔ ~/workspace/serialsim/swig [master|…18] 
15:37 $ make
  CC       serialsim.lo
DPACKAGE_NAME=\"serialsim\" -DPACKAGE_TARNAME=\"serialsim\" -DPACKAGE_VERSION=\"1.0-rc2\" -DPACKAGE_STRING=\"serialsim\ 1.0-rc2\" -DPACKAGE_BUGREPORT=\"minyard@acm.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"serialsim\" -DVERSION=\"1.0-rc2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSTDC_HEADERS=1 -DHAVE_PYTHON=\"3.7\" -python -py3 -o serialsim_wrap.c \
serialsim.i
/bin/bash: -DPACKAGE_TARNAME="serialsim": command not found
make: [Makefile:860: serialsim_wrap.c] Error 127 (ignored)
  CC       serialsim_wrap.lo
gcc: error: serialsim_wrap.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
make: *** [Makefile:482: serialsim_wrap.lo] Error 1

**Comment by cminyard** [comment]
On Mon, Apr 06, 2020 at 12:42:32PM -0700, Scott Bertin wrote:
> After cloning, I ran the reconf script from ser2net, configure, and make. It failed to build and appears that there is a file missing. Full log follows.
> 

Actually, it looks like you need to install swig.

serialsim is kind of a think I just threw together; I haven't spent much
time making sure everything is correct in the build system.

Thanks for the report, I'll add something to error out when it can't
find swig.

-corey

**Comment by sbertin-telular** [comment]
I can confirm that was the problem. I didn't even know swig was a thing.
